Repository dnd-side-project/dnd-10th-7-frontend, pull requests merged in 2024-02, with the labels that each got.

#4 feat : style setting
  package.json
  public/assets/next.svg
  public/assets/vercel.svg
  src/api/queryClient.ts
  src/app/globals.css
  src/app/page.tsx
  src/types/test.ts
  tailwind.config.ts
  yarn.lock
Labels: 😈 chaemin, 🎨 style, 🚚 Chore, ⚙ setting

#7 feature : common component (tab, dropdown, input, textarea)
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/dropdown/Dropdown.tsx
  src/components/dropdown/Dropdown.types.ts
  src/components/dropdown/index.ts
  src/components/input/GrayInput.tsx
  src/components/input/GrayInput.types.ts
  src/components/input/PurPleInput.tsx
  src/components/input/PurPleInput.types.ts
  src/components/input/index.ts
  src/components/tab/Tab.tsx
  src/components/tab/Tab.types.ts
  src/components/tab/TabComponent.tsx
  src/components/tab/index.ts
  src/components/textarea/Textarea.tsx
  src/components/textarea/Textarea.types.ts
  src/components/textarea/index.ts
  tailwind.config.ts
  yarn.lock
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#6 feature : common component (button, tag, modal)
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test-chaemin/page.tsx
  src/components/button/Button.tsx
  src/components/button/Button.types.ts
  src/components/button/index.ts
  src/components/modal/Modal.tsx
  src/components/modal/Modal.types.ts
  src/components/modal/ModalContext.tsx
  src/components/modal/index.ts
  src/components/tag/Tag.tsx
  src/components/tag/Tag.types.ts
  src/components/tag/index.ts
  tailwind.config.ts
  yarn.lock
Labels: 😈 chaemin, 📍 feat, 🎨 style

#14 feature: add textarea error focus
  src/app/test-chaemin/page.tsx
  src/app/test/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/button/index.ts
  src/components/common-components/dropdown/Dropdown.tsx
  src/components/common-components/dropdown/Dropdown.types.ts
  src/components/common-components/dropdown/index.ts
  src/components/common-components/input/GrayInput.tsx
  src/components/common-components/input/GrayInput.types.ts
  src/components/common-components/input/PurPleInput.tsx
  src/components/common-components/input/PurPleInput.types.ts
  src/components/common-components/input/index.ts
  src/components/common-components/tab/Tab.tsx
  src/components/common-components/tab/Tab.types.ts
  src/components/common-components/tab/TabComponent.tsx
  src/components/common-components/tab/index.ts
  src/components/common-components/tag/Tag.tsx
  src/components/common-components/tag/Tag.types.ts
  src/components/common-components/tag/index.ts
  src/components/common-components/textarea/Textarea.tsx
  src/components/common-components/textarea/Textarea.types.ts
  src/components/common-components/textarea/index.ts
  src/components/input/index.ts
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#13 feature: landing page top
  package.json
  public/assets/profile_img.png
  react-ts-slick/package.json
  src/app/page.tsx
  src/app/test-chaemin/page.tsx
  src/app/test/page.tsx
  src/components/common-components/button/dropdown/Dropdown.tsx
  src/components/common-components/button/dropdown/Dropdown.types.ts
  src/components/common-components/button/dropdown/index.ts
  src/components/common-components/modal/Modal.tsx
  src/components/common-components/modal/Modal.types.ts
  src/components/common-components/modal/ModalContext.tsx
  src/components/common-components/modal/index.ts
  src/components/landing/carousel/Carousel.tsx
  src/components/landing/carousel/LandingMid.tsx
  src/components/landing/carousel/LandingTop.tsx
  src/components/landing/carousel/RecommendItem.tsx
  yarn.lock
Labels: 💣 seoyoung, 📍 feat, 🎨 style, ✅ Test

#16 feature : modified tab component
  src/app/test/page.tsx
  src/components/common-components/tab/Tab.tsx
  src/components/common-components/tab/Tab.types.ts
  src/components/common-components/tab/TabComponent.tsx
Labels: 💣 seoyoung, 🔨 fix, 🎨 style, ✅ Test

#19 feat : project list
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test-chaemin/page.tsx
  src/components/common-components/mui/theme.ts
  src/components/common-components/title/Title.tsx
  src/components/common-components/title/index.ts
  src/components/landing/project/Categories.tsx
  src/components/landing/project/ProjectItem.tsx
  src/components/landing/project/ProjectList.tsx
  src/components/landing/project/ProjectTab.tsx
  yarn.lock
Labels: 😈 chaemin, 📍 feat, 🎨 style, ✅ Test

#12 feature : signup modal
  package.json
  src/api/api.ts
  src/api/userAPI.ts
  src/app/RecoilRootWrapper.tsx
  src/app/layout.tsx
  src/app/test-chaemin/page.tsx
  src/app/test/page.tsx
  src/atoms/modal.ts
  src/components/alert-modal/CompleteModal.tsx
  src/components/alert-modal/ErrorModal.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/button/dropdown/Dropdown.tsx
  src/components/common-components/button/dropdown/Dropdown.types.ts
  src/components/common-components/button/dropdown/index.ts
  src/components/common-components/dropdown/Dropdown.tsx
  src/components/common-components/dropdown/Dropdown.types.ts
  src/components/common-components/input/GrayInput.tsx
  src/components/common-components/input/GrayInput.types.ts
  src/components/common-components/input/PurPleInput.tsx
  src/components/common-components/input/index.ts
  src/components/common-components/modal/Modal.tsx
  src/components/common-components/modal/Modal.types.ts
  src/components/common-components/tab/Tab.tsx
  src/components/sign-up/InterestModal.tsx
  src/components/sign-up/LoginModal.tsx
  src/components/sign-up/NicknameModal.tsx
  src/components/sign-up/UserInfoModal.tsx
  yarn.lock
Labels: 😈 chaemin, 📍 feat, ✅ Test

#25 feat : comment
  src/app/test-chaemin/page.tsx
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/comment/ReplyComment.tsx
  src/components/common-components/textarea/Textarea.tsx
Labels: 😈 chaemin, 📍 feat, 🎨 style

#30 feature: mypage profile tab
  src/app/mypage/page.tsx
  src/components/mypage/MyPageFeedBackInfo.tsx
  src/components/mypage/MyPageLevelToolTip.tsx
  src/components/mypage/MyPageProfileTab.tsx
  src/components/mypage/MyPageUserInfo.tsx
  src/types/User.ts
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#32 feature: footer
  public/assets/Sendback_logo.png
  src/app/test/page.tsx
  src/components/footer/Footer.tsx
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#35 design: project register page
  src/app/project/register/Calendar.tsx
  src/app/project/register/RegisterProjectInputContent.tsx
  src/app/project/register/RegisterProjectInputPeriod.tsx
  src/app/project/register/RegisterProjectInputTitle.tsx
  src/app/project/register/RegisterProjectTitle.tsx
  src/app/project/register/ReigsterProjectInputCheck.tsx
  src/components/common-components/checkbox/index.ts
  src/components/common-components/radiocheckbox/RadioCheckBox.tsx
  src/components/common-components/radiocheckbox/RadioCheckBox.types.ts
  src/components/common-components/radiocheckbox/index.ts
Labels: 💣 seoyoung, 🎨 style

#28 feature: sendback page
  src/app/sendback/register/RegisterSendbackInputTitle.tsx
  src/app/sendback/register/RegisterSendbackTitle.tsx
  src/app/sendback/register/RegisterSendbackTitleData.tsx
  src/app/sendback/register/RegisterSendbackUserInfo.tsx
  src/app/sendback/register/page.tsx
  src/components/common-components/input/PurPleInput.tsx
  src/types/Sendback.ts
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#39 feature: sendback register page
  src/app/[projectId]/sendback/register/RegisterSendbackInputTitle.tsx
  src/app/[projectId]/sendback/register/RegisterSendbackTitle.tsx
  src/app/[projectId]/sendback/register/RegisterSendbackTitleData.tsx
  src/app/[projectId]/sendback/register/RegisterSendbackUserInfo.tsx
  src/app/[projectId]/sendback/register/page.tsx
  src/app/project/register/page.tsx
  src/components/project/ProjectSendbackTitleData.tsx
  src/components/project/ProjectSendbackUserInfo.tsx
Labels: 💣 seoyoung, 🎨 style

#36 feature : feedback detail
  package.json
  src/app/feedback/[feedbackId]/page.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/sub-title/SubTitle.tsx
  src/components/common-components/sub-title/index.ts
  src/components/feedback/CaptureModal.tsx
  src/components/feedback/RewardModal.tsx
  src/components/project/ProjectSendbackUserInfo.tsx
  yarn.lock
Labels: 😈 chaemin, 📍 feat, 🎨 style

#37 feature : mypage-profile-edit modal
  src/components/alert-modal/CompleteModal.tsx
  src/components/mypage/MyPageProfileTab.tsx
  src/components/mypage/ProfileEditModal.tsx
  src/components/sign-up/LoginModal.tsx
Labels: 😈 chaemin, 📍 feat, 🎨 style

#45 design: footer 반영
  src/app/page.tsx
  src/components/footer/Footer.tsx
Labels: 💣 seoyoung, 🎨 style

#40 feature: project detail page
  src/app/project/[projectId]/ProjectDetailFeedBackRequest.tsx
  src/app/project/[projectId]/ProjectDetailImage.tsx
  src/app/project/[projectId]/ProjectDetailTeamMemberInfo.tsx
  src/app/project/[projectId]/page.tsx
  src/app/project/[projectId]/styles.module.css
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/landing/carousel/RecommendItem.tsx
  src/components/project/ProjectSendbackUserInfo.tsx
Labels: 💣 seoyoung, 📍 feat, 🎨 style

#18 feature: kakao login
  public/assets/kakao_icon.png
  src/api/api.ts
  src/api/kakaoGetAPI.ts
  src/api/queryClient.ts
  src/app/api/auth/kakao/callback/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/page.tsx
  src/components/ social/KaKaoButton.tsx
  src/context/provider/index.tsx
  src/hooks/useAuth.ts
  yarn.lock
Labels: 💣 seoyoung, 📍 feat, ✅ Test

#47 🔨 Fix: solve import error
  src/app/page.tsx
  src/components/feedback/CaptureModal.tsx
  src/components/feedback/RewardModal.tsx
  src/components/mypage/ProfileEditModal.tsx
Labels: 😈 chaemin, hotfix

#43 feat : header
  src/app/page.tsx
  src/app/test-chaemin/page.tsx
  src/app/test/page.tsx
  src/components/common-components/common/Footer.tsx
  src/components/common-components/common/Header.tsx
  src/components/common-components/dropdown-box/DropdownBox.tsx
  src/components/common-components/dropdown-box/DropdownBox.types.ts
  src/components/common-components/dropdown-box/index.ts
Labels: 😈 chaemin, 📍 feat, 🎨 style

#55 feat : project page
  src/app/layout.tsx
  src/app/page.tsx
  src/app/project/page.tsx
  src/components/common-components/common/Header.tsx
Labels: 😈 chaemin, 📍 feat

#51 feature: project api
  next.config.mjs
  src/api/api.ts
  src/api/feedbackAPI.ts
  src/api/projectAPI.ts
  src/app/project/[projectId]/ProjectDetailFeedBackRequest.tsx
  src/app/project/[projectId]/ProjectDetailTeamMemberInfo.tsx
  src/app/project/[projectId]/page.tsx
  src/app/project/register/RegisterProjectInputImage.tsx
  src/app/project/register/page.tsx
  src/app/test/page.tsx
  src/components/common-components/sub-title/SubTitle.tsx
  src/components/project/ProjectSendbackUserInfo.tsx
  src/context/provider/index.tsx
  src/hooks/useFeedback.ts
  src/hooks/useProject.ts
  src/types/Project.ts
Labels: 💣 seoyoung, 📍 feat

#59 feat : signup api
  src/api/socialAPI.ts
  src/api/userAPI.ts
  src/app/api/auth/google/callback/page.tsx
  src/app/layout.tsx
  src/atoms/modalAtom.ts
  src/components/alert-modal/ErrorModal.tsx
  src/components/common-components/common/Header.tsx
  src/components/signup/NicknameForm.tsx
  src/components/signup/SignUpModal.tsx
  src/hooks/useAuth.ts
Labels: 😈 chaemin, 📍 feat

#61 feat: feedback api
  src/api/feedbackAPI.ts
  src/app/[projectId]/sendback/register/page.tsx
  src/app/page.tsx
  src/app/project/[projectId]/ProjectDetailFeedBackRequest.tsx
  src/app/project/[projectId]/feedback/[feedbackId]/page.tsx
  src/app/project/[projectId]/page.tsx
  src/components/alert-modal/ErrorModal.tsx
  src/components/common-components/common/Header.tsx
  src/components/common-components/dropdown-box/DropdownBox.tsx
  src/components/feedback/CaptureModal.tsx
  src/components/feedback/RewardModal.tsx
  src/components/signup/LoginModal.tsx
  src/hooks/useFeedback.ts
  src/hooks/useProject.ts
Labels: 💣 seoyoung, 📍 feat

#66 feat: mypage profile tab
  src/api/userAPI.ts
  src/app/mypage/page.tsx
  src/components/mypage/MyPageFeedBackInfo.tsx
  src/components/mypage/MyPageLevelToolTip.tsx
  src/components/mypage/MyPageProfileTab.tsx
  src/components/mypage/MyPageUserInfo.tsx
  src/hooks/useMyPage.ts
Labels: 💣 seoyoung, 📍 feat

#68 feat: mypage dropdown
  src/api/projectAPI.ts
  src/app/layout.tsx
  src/components/alert-modal/CheckModal.tsx
  src/components/common-components/common/Header.tsx
  src/components/common-components/dropdown-box/DropdownBox.tsx
  src/components/common-components/dropdown-box/DropdownBox.types.ts
  src/components/landing/project/ProjectItem.tsx
  src/components/landing/project/ProjectTab.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/signup/LoginModal.tsx
  src/hooks/useProject.ts
Labels: 💣 seoyoung, 📍 feat

#69 feat : mypage api
  src/api/mypageAPI.ts
  src/components/landing/project/ProjectItem.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ProfileEditModal.tsx
  src/hooks/useMyPage.ts
Labels: 😈 chaemin, 📍 feat

#56 feat : project list api
  next.config.mjs
  src/api/projectAPI.ts
  src/app/[projectId]/sendback/register/page.tsx
  src/app/api/auth/google/callback/page.tsx
  src/app/page.tsx
  src/app/project/page.tsx
  src/app/project/register/page.tsx
  src/app/test/page.tsx
  src/components/comment/ReplyComment.tsx
  src/components/common-components/dropdown-box/DropdownBox.tsx
  src/components/common-components/input/PurPleInput.tsx
  src/components/common-components/input/PurPleInput.types.ts
  src/components/common-components/pagination/Pagination.tsx
  src/components/common-components/pagination/index.ts
  src/components/landing/project/Categories.tsx
  src/components/landing/project/ProjectItem.tsx
  src/components/landing/project/ProjectList.tsx
  src/components/landing/project/ProjectTab.tsx
  src/components/mypage/MyPageProfileTab.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ProfileEditModal.tsx
  src/hooks/useAuth.ts
  src/hooks/useProject.ts
  src/types/Project.ts
  src/types/User.ts
  src/types/api.ts
Labels: 😈 chaemin, 📍 feat

#64 feat : comment api
  src/api/projectAPI.ts
  src/app/project/[projectId]/page.tsx
  src/app/test-chaemin/page.tsx
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentInput.tsx
  src/components/comment/CommentItem.tsx
  src/components/common-components/textarea/Textarea.tsx
  src/components/mypage/MyPageTab.tsx
  src/hooks/useProject.ts
  src/types/Project.ts
Labels: 😈 chaemin, 📍 feat

#74 design: ui/ux 검토
  package.json
  public/assets/Sendback_logo.png
  public/assets/level/Lv1.png
  public/assets/level/Lv2.png
  public/assets/level/Lv3.png
  public/assets/level/Lv4.png
  public/assets/level/Lv5.png
  public/assets/main_background.png
  public/assets/modal/feedback.png
  public/assets/modal/mypage.png
  public/assets/modal/project.png
  public/assets/modal/reward.png
  public/assets/modal/signup.png
  public/assets/next.svg
  public/assets/profile_img.png
  public/assets/vercel.svg
  src/app/[projectId]/sendback/register/page.tsx
  src/app/page.tsx
  src/app/project/[projectId]/ProjectDetailFeedBackRequest.tsx
  src/app/project/[projectId]/page.tsx
  src/app/project/register/page.tsx
  src/components/common-components/common/Header.tsx
  src/components/feedback/RewardModal.tsx
  src/components/landing/carousel/LandingMid.tsx
  src/components/landing/carousel/LandingTop.tsx
  src/components/landing/carousel/RecommendItem.tsx
  src/components/mypage/MyPageFeedBackInfo.tsx
  yarn.lock
Labels: 💣 seoyoung, 🎨 style

#77 refactor: 프로젝트 수정 라우터 막기
  src/components/common-components/dropdown-box/DropdownBox.tsx
Labels: 💣 seoyoung, 🔨 fix

#75 design/fix : UI/UX
  src/app/mypage/page.tsx
  src/app/project/page.tsx
  src/components/comment/CommentBox.tsx
  src/components/comment/CommentInput.tsx
  src/components/common-components/button/Button.tsx
  src/components/common-components/button/Button.types.ts
  src/components/common-components/dropdown-box/DropdownBox.tsx
  src/components/common-components/textarea/Textarea.tsx
  src/components/common-components/textarea/Textarea.types.ts
  src/components/landing/project/ProjectItem.tsx
  src/components/landing/project/ProjectList.tsx
  src/components/landing/project/ProjectTab.tsx
  src/components/mypage/MyPageEmptyView.tsx
  src/components/mypage/MyPageTab.tsx
  src/components/mypage/ProfileEditModal.tsx
Labels: 😈 chaemin, 🔨 fix, 🎨 style
